### ISSUE TITLE
创建客户端的时候opts参数传入['send_yield => true']即可解决

### ISSUE THREAD

**Issue by bnubobby** [swoole/grpc#19]
创建客户端的时候opts参数传入['send_yield => true']即可解决

_Originally posted by @twose in https://github.com/swoole/grpc/issues/18#issuecomment-616376201_

已传入  ['send_yield => true']  ，问题依旧

**Comment by yuqx1561** [comment]
在哪里传参的 ，我这怎么没找到这个参数配置
