### ISSUE TITLE
Uncaught Error: Class 'Swoole\Coroutine\Http2\Client' not found

### ISSUE THREAD

**Issue by Chrisdowson** [swoole/grpc#28]
大家又遇到和我一样的问题吗？
![image](https://user-images.githubusercontent.com/6045803/104698126-d30de900-574b-11eb-8ecd-6bc42bb14365.png)
执行`php -i`
![image](https://user-images.githubusercontent.com/6045803/104698242-094b6880-574c-11eb-9f53-0e1ba91b78f6.png)

**Comment by sy-records** [comment]
重新编译swoole，增加`--enable-http2`选项

**Comment by grayTele** [comment]
我这边使用这个方法编译后还是不行呢?在dockerfile文件中
RUN pecl install https://pecl.php.net/get/swoole-4.8.3.tgz --enable-http2 && docker-php-ext-enable swoole
